-- MySQL Script generated by MySQL Workbench
-- Sun Jul  3 21:21:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sportix_arg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sportix_arg` ;

-- -----------------------------------------------------
-- Schema sportix_arg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sportix_arg` DEFAULT CHARACTER SET utf8mb4 ;
USE `sportix_arg` ;

-- -----------------------------------------------------
-- Table `sportix_arg`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`brand` ;
CREATE TABLE IF NOT EXISTS `sportix_arg`.`brand` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `sportix_arg`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`category` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `sportix_arg`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`country` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`country` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `sportix_arg`.`detalle_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`detalle_producto` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`detalle_producto` (
  `id` int(11) NOT NULL,
  `id_productos` int(11) NOT NULL,
  `cantidad` int(11) DEFAULT NULL,
  `date` datetime NOT NULL,
  `precio` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_DP_P` (`id_productos`),
  CONSTRAINT `FK_DP_O` FOREIGN KEY (`id`) REFERENCES `order` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_DP_P` FOREIGN KEY (`id_productos`) REFERENCES `productos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `sportix_arg`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`gender` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`gender` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `sportix_arg`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`order` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `total` decimal(10,0) NOT NULL,
  `date` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_O_user` (`iduser`),
  CONSTRAINT `FK_O_user` FOREIGN KEY (`iduser`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `sportix_arg`.`sizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`sizes` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`sizes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sizes` varchar(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `sportix_arg`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`productos` ;

CREATE TABLE `productos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `description` text NOT NULL,
  `category` int(11) NOT NULL,
  `size` int(11) NOT NULL,
  `date` date NOT NULL,
  `price` int(11) NOT NULL,
  `gender` int(11) NOT NULL,
  `brand` int(11) NOT NULL,
  `file` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_P_G` (`gender`),
  KEY `FK_P_B` (`brand`),
  KEY `FK_P_S` (`size`),
  KEY `FK_P_Cat` (`category`),
  CONSTRAINT `FK_P_B` FOREIGN KEY (`brand`) REFERENCES `brand` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_P_Cat` FOREIGN KEY (`category`) REFERENCES `category` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_P_G` FOREIGN KEY (`gender`) REFERENCES `gender` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_P_S` FOREIGN KEY (`size`) REFERENCES `sizes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `sportix_arg`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`state` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`state` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `sportix_arg`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`users` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fullName` varchar(45) NOT NULL,
  `email` varchar(100) NOT NULL,
  `idGender` int(11) NOT NULL,
  `password` varchar(45) NOT NULL,
  `birthday` date NOT NULL,
  `phone` int(11) NOT NULL,
  `idCountry` int(11) NOT NULL,
  `idState` int(11) NOT NULL,
  `newsletter` varchar(3) NOT NULL,
  `file` varchar(100) NOT NULL,
  `idRoles` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_U_G` (`idGender`),
  KEY `FK_U_C` (`idCountry`),
  KEY `FK_U_S` (`idState`),
  KEY `FK_U_R` (`idRoles`),
  CONSTRAINT `FK_U_C` FOREIGN KEY (`idCountry`) REFERENCES `country` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_U_G` FOREIGN KEY (`idGender`) REFERENCES `gender` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_U_R` FOREIGN KEY (`idRoles`) REFERENCES `roles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_U_S` FOREIGN KEY (`idState`) REFERENCES `state` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4;


-- -----------------------------------------------------
-- Table `sportix_arg`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sportix_arg`.`roles` ;

CREATE TABLE IF NOT EXISTS `sportix_arg`.`roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(15) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

