-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 17:21:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Brandcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(500) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `size` VARCHAR(10) NOT NULL,
  `date` DATE NOT NULL,
  `price` INT NOT NULL,
  `gendre` VARCHAR(45) NOT NULL,
  `id_Brand(FK)` VARCHAR(45) NOT NULL,
  `file` VARCHAR(100) NOT NULL,
  `discount` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `description_UNIQUE` (`description` ASC) VISIBLE,
  CONSTRAINT `id_Brand`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Brand` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NOT NULL,
  `gendre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal` INT(10) NOT NULL,
  `birthday` DATE NOT NULL,
  `phone` INT(25) NOT NULL,
  `file` VARCHAR(100) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fullName_UNIQUE` (`fullName` ASC) VISIBLE,
  UNIQUE INDEX `file_UNIQUE` (`file` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gendre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gendre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products_has_Gendre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products_has_Gendre` (
  `Products_id` INT NOT NULL,
  `Gendre_id` INT NOT NULL,
  PRIMARY KEY (`Products_id`, `Gendre_id`),
  INDEX `fk_Products_has_Gendre_Gendre1_idx` (`Gendre_id` ASC) VISIBLE,
  INDEX `fk_Products_has_Gendre_Products1_idx` (`Products_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Gendre_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Gendre_Gendre1`
    FOREIGN KEY (`Gendre_id`)
    REFERENCES `mydb`.`Gendre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Gendre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Gendre` (
  `Users_id` INT NOT NULL,
  `Gendre_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `Gendre_id`),
  INDEX `fk_Users_has_Gendre_Gendre1_idx` (`Gendre_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Gendre_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Gendre_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Gendre_Gendre1`
    FOREIGN KEY (`Gendre_id`)
    REFERENCES `mydb`.`Gendre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
